# Regenerates cmake/WasiSdkChecksums.cmake from the wasi-sdk GitHub releases API.
#
#   cmake [-DMIN_VERSION=26] [-DOUTPUT=<path>] -P tools/update-checksums.cmake
#
# Set GITHUB_TOKEN in the environment to lift the anonymous API rate limit.
#
# Only releases whose assets carry a `digest` field are emitted; GitHub started
# publishing those with wasi-sdk-26, so older releases cannot be pinned from the
# API alone and are skipped with a warning.

cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED MIN_VERSION)
  set(MIN_VERSION 26)
endif()
if(NOT DEFINED OUTPUT)
  set(OUTPUT "${CMAKE_CURRENT_LIST_DIR}/../cmake/WasiSdkChecksums.cmake")
endif()

set(api_url "https://api.github.com/repos/WebAssembly/wasi-sdk/releases?per_page=100")
set(response "${CMAKE_CURRENT_LIST_DIR}/../.releases.json")

set(headers HTTPHEADER "Accept: application/vnd.github+json")
if(DEFINED ENV{GITHUB_TOKEN} AND NOT "$ENV{GITHUB_TOKEN}" STREQUAL "")
  list(APPEND headers HTTPHEADER "Authorization: Bearer $ENV{GITHUB_TOKEN}")
endif()

message(STATUS "Fetching ${api_url}")
file(DOWNLOAD "${api_url}" "${response}" STATUS status ${headers})
list(GET status 0 code)
if(NOT code EQUAL 0)
  list(GET status 1 reason)
  file(REMOVE "${response}")
  message(FATAL_ERROR "Failed to query the releases API: ${reason}")
endif()

file(READ "${response}" json)
file(REMOVE "${response}")

string(JSON error_type ERROR_VARIABLE ignored TYPE "${json}")
if(NOT error_type STREQUAL "ARRAY")
  message(FATAL_ERROR
    "Unexpected releases API response. If this says 'rate limit exceeded', "
    "set GITHUB_TOKEN and retry.\n${json}")
endif()

set(versions "")
set(entries "")
set(skipped "")

string(JSON release_count LENGTH "${json}")
math(EXPR last_release "${release_count} - 1")
foreach(r RANGE 0 ${last_release})
  string(JSON release GET "${json}" ${r})
  string(JSON tag GET "${release}" "tag_name")
  string(JSON prerelease GET "${release}" "prerelease")

  if(prerelease)
    continue()
  endif()
  if(NOT tag MATCHES "^wasi-sdk-([0-9]+)$")
    continue()
  endif()
  set(major "${CMAKE_MATCH_1}")
  if(major LESS MIN_VERSION)
    continue()
  endif()

  string(JSON assets GET "${release}" "assets")
  string(JSON asset_count LENGTH "${assets}")
  math(EXPR last_asset "${asset_count} - 1")

  set(release_entries "")
  set(release_version "")
  foreach(a RANGE 0 ${last_asset})
    string(JSON asset GET "${assets}" ${a})
    string(JSON name GET "${asset}" "name")
    if(NOT name MATCHES "^wasi-sdk-([0-9]+\\.[0-9]+)-(arm64|x86_64)-(linux|macos|windows)\\.tar\\.gz$")
      continue()
    endif()
    set(version "${CMAKE_MATCH_1}")
    set(host_id "${CMAKE_MATCH_2}-${CMAKE_MATCH_3}")

    string(JSON digest_type ERROR_VARIABLE ignored TYPE "${asset}" "digest")
    if(NOT digest_type STREQUAL "STRING")
      continue()
    endif()
    string(JSON digest GET "${asset}" "digest")
    if(NOT digest MATCHES "^sha256:([0-9a-f]+)$")
      continue()
    endif()
    set(sha256 "${CMAKE_MATCH_1}")

    string(REPLACE "." "_" key "${version}")
    set(release_version "${version}")
    string(APPEND release_entries
      "set(_wasi_sdk_asset_${key}_${host_id} \"${name}\")\n"
      "set(_wasi_sdk_sha256_${key}_${host_id} \"${sha256}\")\n")
  endforeach()

  if(release_entries STREQUAL "")
    list(APPEND skipped "${tag}")
    continue()
  endif()

  list(APPEND versions "${release_version}")
  string(APPEND entries "\n# ${tag}\n${release_entries}")
endforeach()

if(versions STREQUAL "")
  message(FATAL_ERROR "No releases with publishable digests were found.")
endif()

list(SORT versions COMPARE NATURAL)
list(REVERSE versions)

if(NOT skipped STREQUAL "")
  string(REPLACE ";" ", " skipped_text "${skipped}")
  message(WARNING
    "Skipped releases without asset digests (pin these manually if needed): ${skipped_text}")
endif()

string(REPLACE ";" ";" versions_text "${versions}")
file(WRITE "${OUTPUT}"
"# Generated by tools/update-checksums.cmake -- do not edit by hand.
#
# Maps a wasi-sdk version and host identifier onto the published release asset
# name and its SHA256 digest.

include_guard(GLOBAL)

set(WASI_SDK_KNOWN_VERSIONS \"${versions_text}\")
${entries}")

list(LENGTH versions version_count)
message(STATUS "Wrote ${version_count} version(s) to ${OUTPUT}")
